[package]
name = "event-stream"
version = "0.0.0"
authors = ["Thomas Ball <tomoliverball@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
simple_logger = "4.1.0"
regex = "1.8.1"
serde_regex = "1.1.0"
dotenv = "0.15.0"
log = "0.4.17"
bytes = "1.4.0"
anyhow = "1.0.71"
async-trait = "^0.1.68"
tokio = { version = "1.28.1", features = ["full"] }
warp = "0.3.5"
lambda_payloads = { path = "../payloads" }
lichess_events = { path = "../../lib/events" }
lichess_api = { path = "../../lib/lichess" }
reqwest = { version = "0.11.18", features = ["rustls-tls", "json", "stream"] , default-features = false}
rusoto_core = { version = "0.48.0", features = ["rustls"] , default-features = false}
rusoto_lambda = { version = "0.48.0", features = ["rustls"] , default-features = false}
rusoto_dynamodb = { version = "0.48.0", features = ["rustls"] , default-features = false}
