[package]
name = "hyperopic-cli"
version = "0.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
anyhow = "1.0.71"
hyperopic = {path = "../hyperopic"}
lazy_static = "1.5.0"
regex = "1.11.1"
simple_logger = "5.0.0"
log = "0.4.17"
