[package]
name = "testing"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyperopic = { path = "../hyperopic" }
lichess_api = { path = "../../lib/lichess" }
lichess_events = { path = "../../lib/events" }
lichess_game = { path = "../../lib/game" }
openings = { path = "../../lib/openings" }
async-trait = "0.1.68"
tokio = { version = "1.28.1", features = ["full"] }
clap = { version = "4.3.0", features = ["derive"] }
log = "0.4.17"
simple_logger = "5.0.0"
anyhow = "1.0.71"
rand = "0.*"
chrono = "0.4.26"
lazy_static = "1.4.0"
