[package]
name = "chessmove"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyperopic = { path = "../../engine/hyperopic" }
lambda_payloads = { path = "../payloads" }
lambda_runtime = "0.8.0"
tokio = "1.0"
serde_json = "1.0.96"
simple_logger = "5.0.0"
log = "0.4.17"
anyhow = "1.0.72"
lichess_api = { path = "../../lib/lichess" }
openings = { path = "../../lib/openings" }
